### ISSUE TITLE
serial: extend serial schema to accept job backend configuration

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-commons#118]
In [Condor-Slurm-Demo](https://github.com/orgs/reanahub/projects/3) sprint we will implement the first prototype to submit jobs to two new job backends (HTCondor and Slurm) using Serial workflows. In order to give users the possibility to choose which job backend to run their jobs on we should extend the [serial specification](https://github.com/reanahub/reana-commons/blob/master/reana_commons/serial.py#L17-L53) syntax.

To ilustrate we can take the [reana-demo-root6-roofit reana.yaml](https://github.com/reanahub/reana-demo-root6-roofit/blob/master/reana.yaml) and modify it:

```diff
version: 0.5.0
inputs:
  files:
    - code/gendata.C
    - code/fitdata.C
  parameters:
    events: 20000
    data: results/data.root
    plot: results/plot.png
workflow:
  type: serial
  specification:
    steps:
+     - name: mkdir-results
+       description: Create results directory.
+       environment: 'reanahub/reana-env-root6'
+       backend:
+         name: Kubernetes
        commands:
        - mkdir -p results
+       outputs:
+         - results/
+     - name: gendata
+       description: Generate data depending on the number of `events`.
+       environment: 'reanahub/reana-env-root6'
+       backend:
+         name: HTCondor
        commands:
        - root -b -q 'code/gendata.C(${events},"${data}")' | tee gendata.log
+       inputs:
+         - code/gendata.C
+       outputs:
+         - gendata.log
+         - results/data.root
+     - name: fitdata
+       description: Fit data and generate final plot.
+       environment: 'reanahub/reana-env-root6'
+       backend:
+         name: Slurm
        commands:
        - root -b -q 'code/fitdata.C("${data}","${plot}")' | tee fitdata.log
+       inputs:
+         - code/fitdata.C
+       outputs:
+         - fitdata.log
+         - results/plot.png
outputs:
  files:
    - results/plot.png
```

Note that `workflow.specification.steps[].name` and `workflow.specification.steps[].description` are optional, but `workflow.specification.steps[].inputs` and `workflow.specification.steps[].outputs` would be really helpful so pushing/pulling inputs/outputs to/from the job workspaces would be easier (https://github.com/reanahub/reana-job-controller/issues/143, https://github.com/reanahub/reana-job-controller/issues/142).

**Comment by roksys** [comment]
I think this also can be closed. @diegodelemos  what do you think?

**Comment by tiborsimko** [comment]
@roksys I think it can be closed, but you can make PRs to the respective `reana-demo-*` where you have been testing HTCondor and perhaps start adding step names there...
