### ISSUE TITLE
New kubernetes version (10.1.0) incompatible with PyYAML in tag 0.6.0

### ISSUE THREAD

**Issue by khurtado** [reanahub/reana-commons#180]
Hello,

On March 12, `kubernetes` released versions 10.1.0 to 11.0.0
https://pypi.org/project/kubernetes/#history

This is now installed by pip rather than 10.0.1. The problem is, we use PyYAML 5.3.1 and:
- Kubernetes 10.0.1 requires PyYAML >= 3.12
- Kubertenes 10.1.0 requires PyYAML ~= 3.12

Should we update tag 0.6.0 to use 10.0.1 explictly here?
https://github.com/reanahub/reana-commons/blob/v0.6.0/setup.py#L32

```
======
Collecting kubernetes==10.0.1
  Using cached kubernetes-10.0.1-py2.py3-none-any.whl (1.5 MB)
Collecting pyyaml>=3.12

======
But when I try 10.1.0 instead, I get:
====
Collecting kubernetes==10.1.0
 Using cached kubernetes-10.1.0.tar.gz (689 kB)
Collecting pyyaml~=3.12
====
```

**Comment by diegodelemos** [comment]
Hello @khurtado, you could do the same as we did in latest master (see [here](https://github.com/reanahub/reana-commons/pull/173)) and make a PR against  [`maint-0.6`](https://github.com/reanahub/reana-commons/pull/173) as long as [`make ci`](https://github.com/reanahub/reana/blob/080898ffc13a1edf3d0d3ec7c7e9599c53bbf369/Makefile#L178) passes.

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana-commons/pull/183.
