### ISSUE TITLE
tests: fail while running with ubuntu-20.04 on GA

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-commons#238]
> Tests are not passing with `ubuntu-20.04` because of directory hash mismatch (`calculate_hash_of_dir` used to calculate it). Error can be found [here](https://github.com/audrium/reana-commons/runs/1417421539?check_suite_focus=true). With `ubuntu-18.04` it works fine.

_Originally posted by @audrium in https://github.com/reanahub/reana-commons/issues/237#issuecomment-729632233_

> Since it [wasn't happening before](https://github.com/reanahub/reana-commons/actions/runs/358126199), can you reproduce it locally? I would have guessed it would be somehow related to https://github.com/reanahub/reana-workflow-controller/commit/470171808bdb21e7917671c54fe2e0331f1ee67a, but it isn't because [if the directory doesn't exist it would return `-1`](https://github.com/reanahub/reana-commons/blob/737a2f6da14170db0fa506a0c4129a491872b52c/reana_commons/utils.py#L72) not a different hash. Some very wild guesses:

- Could something be wrong with the workspace, e.g. it already existed and had something else inside? (see [possibility](https://github.com/reanahub/pytest-reana/blob/8315bc72d42aba954873149a8f53416ab48be155/pytest_reana/fixtures.py#L445))
- Could it be that md5 behaves differently in this platform? see [here](https://docs.python.org/3/library/hashlib.html#hashlib.algorithms_guaranteed) (I don't think so since this was passing in the past.

_Originally posted by @diegodelemos in https://github.com/reanahub/reana-commons/issues/237#issuecomment-729711113_

**Comment by mvidalgarcia** [comment]
Fixed by https://github.com/reanahub/reana-commons/commit/24fd7662feb639a5a54140bd119e96775bf981c9
